const emojiDictionary = [
    {
      emoji: "👍",
      description: "Good job, keep up the good work",
      sentiment: 3,
      emoji_name: "Thumbs Up",
      emoji_kw: ["positive", "approval", "agreement"],
    },
    {
      emoji: "📝",
      description: "Good writing, nice paper",
      sentiment: 3,
      emoji_name: "Memo",
      emoji_kw: ["writing", "note-taking", "documentation"],
    },
    {
      emoji: "🎯",
      description: "You are on the right track, good attention to details",
      sentiment: 3,
      emoji_name: "Direct Hit",
      emoji_kw: ["precision", "accuracy", "goal"],
    },
    {
      emoji: "😕",
      description: "Received, pay attention next time",
      sentiment: -3,
      emoji_name: "Confused Face",
      emoji_kw: ["confusion", "uncertainty", "puzzlement"],
    },
    {
      emoji: "😔",
      description: "Bad writing, bad paper",
      sentiment: -3,
      emoji_name: "Pensive Face",
      emoji_kw: ["sadness", "disappointment", "downcast"],
    },
    {
      emoji: "🔄",
      description: "Keep trying, not there yet",
      sentiment: 0,
      emoji_name: "Counterclockwise Arrows",
      emoji_kw: ["retry", "change", "start over"],
    },
    {
      emoji: "📖",
      description: "Good effort, keep practicing",
      sentiment: 2,
      emoji_name: "Open Book",
      emoji_kw: ["reading", "learning", "education"],
    },
    {
      emoji: "🤔",
      description: "Your paper is unclear, thesis unclear",
      sentiment: -2,
      emoji_name: "Thinking Face",
      emoji_kw: ["thoughtfulness", "contemplation", "pondering"],
    },
    {
      emoji: "📚",
      description: "I like how it is turning out, good first draft",
      sentiment: 2,
      emoji_name: "Books",
      emoji_kw: ["books", "studying", "knowledge"],
    },
    {
      emoji: "❌",
      description: "No credit, zero credit",
      sentiment: -3,
      emoji_name: "Cross Mark",
      emoji_kw: ["failure", "rejection", "not allowed"],
    },
    {
      emoji: "🚫",
      description: "You did not follow the instructions, follow the rubric",
      sentiment: -2,
      emoji_name: "Prohibited",
      emoji_kw: ["prohibition", "restriction", "not following"],
    },
    {
      emoji: "🎉",
      description: "Great job showing all the work, amazing work",
      sentiment: 3,
      emoji_name: "Party Popper",
      emoji_kw: ["celebration", "excitement", "success"],
    },
    {
      emoji: "😊",
      description: "I really enjoyed reading your paper, I like what you wrote",
      sentiment: 3,
      emoji_name: "Smiling Face",
      emoji_kw: ["happiness", "contentment", "positive"],
    },
    {
      emoji: "❓",
      description: "What is this? Poor job",
      sentiment: -2,
      emoji_name: "Question Mark",
      emoji_kw: ["question", "curiosity", "uncertainty"],
    },
    {
      emoji: "📈",
      description: "Good effort, but some answers were wrong. Consider reading textbook",
      sentiment: 1,
      emoji_name: "Chart Increasing",
      emoji_kw: ["growth", "progress", "improvement"],
    },
    {
      emoji: "👏",
      description: "Good job, nice paper",
      sentiment: 2,
      emoji_name: "Clapping Hands",
      emoji_kw: ["applause", "appreciation", "recognition"],
    },
    {
      emoji: "📑",
      description: "Amazing paper, perfect paper",
      sentiment: 3,
      emoji_name: "Bookmark Tabs",
      emoji_kw: ["document", "report", "well-prepared"],
    },
    {
      emoji: "😢",
      description: "Sad, awful draft",
      sentiment: -3,
      emoji_name: "Crying Face",
      emoji_kw: ["sadness", "disappointment", "upset"],
    },
    {
      emoji: "📋",
      description: "Show work, good job getting the right answers, but please resubmit this showing all the work",
      sentiment: 1,
      emoji_name: "Clipboard",
      emoji_kw: ["work", "demonstration", "presentation"],
    },
    {
      emoji: "📉",
      description: "Bad answers, bad draft",
      sentiment: -2,
      emoji_name: "Chart Decreasing",
      emoji_kw: ["decrease", "decline", "negative trend"],
    },
    {
      emoji: "🏅",
      description: "Great paper, best paper ever",
      sentiment: 3,
      emoji_name: "Sports Medal",
      emoji_kw: ["achievement", "success", "excellence"],
    },
    {
      emoji: "😃",
      description: "Amazing, awesome, great work",
      sentiment: 3,
      emoji_name: "Smiling Face",
      emoji_kw: ["joy", "happiness", "positive"],
    },
    {
      emoji: "💡",
      description: "I can do hard things, mistakes are proof that you’re trying",
      sentiment: 2,
      emoji_name: "Light Bulb",
      emoji_kw: ["idea", "innovation", "creativity"],
    },
    {
      emoji: "➕",
      description: "Choose your own emoji",
      sentiment: 0,
      emoji_name: "Plus Sign",
      emoji_kw: ["addition", "inclusivity", "combination"],
    },
  ];
  
  export default emojiDictionary;
  